language: node_js
node_js:
- node
services:
- docker
- ntp
addons:
  apt:
    packages:
    - libgif-dev
before_install: npm install -g npm@'>=2.13.5'
script:
- npm test
- docker build -t clems4ever/authelia .
- docker-compose build
- docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
- docker-compose -f docker-compose.yml -f docker-compose.dev.yml run test
- docker-compose -f docker-compose.yml -f docker-compose.dev.yml down
- docker-compose up -d
- sleep 5
- ./scripts/check_services.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push clems4ever/authelia;
    fi

deploy:
  provider: npm
  email: clement.michaud34@gmail.com
  api_key:
    secure: Hj09zw6uHWWRm9WtVSluy1XdISQGQWC3QElT03EuOfn6Mw/4A4Lj5pkvas+cb5y4aGdhQwaldYtKMMQKQ2ASCHcwHF780fkr+bmUjQr3BwrnJn/HsWrg1Q3jcRfY2GmI+hrDlP0/G534132EKxwDGusNSd6atDsQkkCfWDLuRZxkIqYazpanRBUI2jro65f4xX0X1mRgsBEp0gx+m0rFx/yuCkjoDoSlseEJ/NuyaR5N+JervKdrE6K3TrzJ1trnI5L00dwtgiYqlqyXaV8NMR2AOTr/vQlnnjZvkdTZGcKAFMWv3vjTecfp/Z3RW4saRR4CIJKC4JozE70+WMLqmo11br9q58zSrmKjOfkhf6FXaNHIJc/eQr3+PFzhW9DCVcNfcBh5wTVgTlLEp9845FaBdzjH40K0J4OrSnBhWDW14S7fXurTJafR6Ycxhi17vN2oEsT8XcTg2kcrnplMtt5Ylnkb4kYeVIk9cpeTvYtFjlzWPsxZhtURReY+Inbtt8nYThicqjBHHuDpBmyb0aafTYF5qQLx343KBfwFrDHPZXbglZ8Q97OAS9G0LzxkmYf+pIgW7inGsuB4CW6TPNCTZmVo6O2Ov9S4J/aXRfQSbmZa7e3gHP9pbMPhfw4P0ecpbCzRJzXrQXZcet6oIHMCqLB4qOB8KR4/IHplbaE=
  on:
    tags: true
notifications:
  email:
    recipients:
    - clement.michaud34@gmail.com
    on_success: change
    on_failure: always

